// Code generated by templ@v0.2.364 DO NOT EDIT.

package templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Nav_Bar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div class=\"topNav\"><div hx-push-url=\"true\" hx-target=\"#page\" hx-swap=\"outerHTML\" hx-boost=\"true\" hx-get=\"/home\">")
		if err != nil {
			return err
		}
		var_2 := `Home`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div hx-push-url=\"true\" hx-target=\"#page\" hx-swap=\"outerHTML\" hx-boost=\"true\" hx-get=\"/posts\">")
		if err != nil {
			return err
		}
		var_3 := `Posts`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div hx-push-url=\"true\" hx-target=\"#page\" hx-swap=\"outerHTML\" hx-boost=\"true\" hx-get=\"/drama\">")
		if err != nil {
			return err
		}
		var_4 := `Drama`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
